eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/,http://eureka3:8763/eureka/
#    register-with-eureka: false
spring:
  application:
    name: eureka-server
server:
  port: 8762