eureka:
  client:
    service-url:
      defaultZone: http://eureka2:8762/eureka/, http://eureka3:8763/eureka/
#    register-with-eureka: false
spring:
  application:
    name: eureka-server
server:
  port: 8761